### PR TITLE
Exxxxxtendedddddd

### PR DESCRIPTION
**Pull request by yoyurec**
Em... I had time and a good mood so did some BIGGGGGgggg update ))

* Code
  * Refactored, simplified and splitted
  * DOM elements replaced to CSS pseudo-elements + CSS variables
  * Page type / routes checking changed
  * Error handling
  * Bugfixing

* Features
  * Local assets link (`../assets/...........img`) support added
  * Separate Journal/Page icon and banner settings
  * Default banners cached (base64 encoded to avoid URL requests)
  * Possibility to disable defaults (show only when the page has **props**)
  * Home page: big icon for first journal item, small for others
  * Autoupdate page on settings change
  * Autoupdate page on props change
  * Global CSS `body` classes (`is-icon-active`, `.is-banner-active`)added for plugin itself and theme developers needs

### CODE REVIEW

**Comment by sawhney17** [comment]
Amazing! Going to give it a review

**Comment by sawhney17** [comment]
Looks good. Only one concern, why have you kept a 3000ms timeout initially?

Changing it to 100 makes no discernible difference to me.

**Comment by yoyurec** [comment]
there are 2 timeouts:
* 3000 - 1 for render on page load (need time to all data ready), 
* listeners, also need some time. but they are not so critical and can be deferred even more ))

**Comment by yoyurec** [comment]
will retest again... 2000, 1000, 500. 100ms...
maybe LS it was slower b'cose of opened devTools....

**Comment by sawhney17** [comment]
That could be it. Here is a loom video at 100 for me. https://www.loom.com/share/5bd5bbf4802e4a52afb8bf92fe4becf1

**Comment by sawhney17** [comment]
That one was only 100 for the first timeout, this is 100 fro every timeout. 

https://www.loom.com/share/3ff2c02364f54c299184dd037c83877c

**Comment by yoyurec** [comment]
looks like you tested on veeeery simple pages ))
LS with lots of plugins + heavy page works slow.
somehow 3000ms was magic number...

https://www.loom.com/share/c4a29d6660b14566a6cab8fa84c0eb95

BUT for superheavy it need even more...

as we have approach "prop image -> default image -> no image", rendering ALWAYS starts with reading props. and its (reading) as fast as faster\simplier page content..
so there always be pages with custom url in props, but on LS first init/reload it will show default/no image b'cose data was not ready
... and JS `await` didn't help as expected
_(
me: "ok, page! be as slow as you want, i'm using async - i'll wait as much as needed, and render banner automagically!"
page "fck u! " 
me: 🤔
)_

**Comment by yoyurec** [comment]
will you post release message on channel `plugins-updates`?
i'm waiting to post my theme update also right after you ))

**Comment by yoyurec** [comment]
oh, i thought about this but forgot....

**Pull request merged**
